name: FTP Feltoltes
on:
  push:
    branches:
      - memoriz  # Ez figyeli a te branchedet

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Kod letoltese
        uses: actions/checkout@v4

      - name: Feltoltes FTP-re
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /web/  # Ide írd az FTP mappát (pl. /public_html/), ha nem a főbe akarod
